package dambi.rest_api.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import dambi.rest_api.model.Partida;
import dambi.rest_api.repository.PartidaRepository;

@Service
public class PartidaService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PartidaRepository partidaRepository;

    public Partida savePartida(Partida partida) {
        return partidaRepository.save(partida);

    }

    public Iterable<Partida> getAllPartidak() {
        // This returns a JSON or XML with the users
        return partidaRepository.findAll();
    }

    /*
     * public Optional<Partida> getpartida( id) {
     * // This returns a JSON or XML with the users
     * return partidaRepository.findById(id);
     * }
     */
    public void deletePartida(int id) {
        partidaRepository.deleteById(id);
    }
}
